name: PyTest with coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test python API
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Run image
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: "1.8.2"
    - name: Install requirements
      run: poetry install
    - name: Run tests and collect coverage
      run: poetry run pytest --cov=pygolomb --cov-report xml:coverage.xml tests/
    - run: ls -a
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
